import { createServer } from 'node:http'
import { readFile, writeFile, mkdir, unlink } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { extname, join, normalize } from 'node:path'
import { fileURLToPath } from 'node:url'
import { DatabaseSync } from 'node:sqlite'
import crypto from 'node:crypto'
import { requestAnalysis } from './ai-provider.js'
import { fingerprint, findCopy } from './originality.js'
import { searchPlaces, guessLocationName } from './geocode.js'

const root = join(fileURLToPath(new URL('.', import.meta.url)), '..')
const dataDir = join(root, 'data')
const uploadsDir = join(root, 'uploads')
await mkdir(dataDir, { recursive: true }); await mkdir(uploadsDir, { recursive: true })
const db = new DatabaseSync(join(dataDir, 'shotmap.sqlite'))
db.exec('CREATE TABLE IF NOT EXISTS image_fingerprints (photo_id INTEGER PRIMARY KEY REFERENCES photos(id) ON DELETE CASCADE, sha256 TEXT NOT NULL, visual_hash TEXT NOT NULL, canonical TEXT NOT NULL)')
try { db.exec('ALTER TABLE photos ADD COLUMN error TEXT') } catch {}
try { db.exec('ALTER TABLE photos ADD COLUMN ai_model TEXT') } catch {}
db.exec(`PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY, username TEXT UNIQUE NOT NULL, email TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'user', created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS places (id INTEGER PRIMARY KEY, name TEXT NOT NULL, city TEXT NOT NULL, country TEXT NOT NULL, latitude REAL, longitude REAL, description TEXT, average_score INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS photos (id INTEGER PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id), place_id INTEGER REFERENCES places(id), image_url TEXT NOT NULL, title TEXT NOT NULL, description TEXT DEFAULT '', taken_at TEXT, created_at TEXT NOT NULL, ai_score INTEGER NOT NULL, composition INTEGER NOT NULL, lighting INTEGER NOT NULL, sharpness INTEGER NOT NULL, colors INTEGER NOT NULL, visual_quality INTEGER NOT NULL, community_score REAL NOT NULL DEFAULT 0, likes INTEGER NOT NULL DEFAULT 0, views INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS likes (user_id INTEGER NOT NULL REFERENCES users(id), photo_id INTEGER NOT NULL REFERENCES photos(id), created_at TEXT NOT NULL, PRIMARY KEY(user_id, photo_id));
CREATE TABLE IF NOT EXISTS ratings (user_id INTEGER NOT NULL REFERENCES users(id), photo_id INTEGER NOT NULL REFERENCES photos(id), score INTEGER NOT NULL CHECK(score BETWEEN 1 AND 5), created_at TEXT NOT NULL, PRIMARY KEY(user_id, photo_id));
CREATE TABLE IF NOT EXISTS favorites (user_id INTEGER NOT NULL REFERENCES users(id), photo_id INTEGER NOT NULL REFERENCES photos(id), created_at TEXT NOT NULL, PRIMARY KEY(user_id, photo_id));`)
db.exec(`CREATE TABLE IF NOT EXISTS place_favorites (user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, place_id INTEGER NOT NULL REFERENCES places(id) ON DELETE CASCADE, created_at TEXT NOT NULL, PRIMARY KEY(user_id, place_id));`)
db.exec(`CREATE TABLE IF NOT EXISTS sessions (token TEXT PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, expires_at TEXT NOT NULL);`)
db.exec(`CREATE TABLE IF NOT EXISTS reports (id INTEGER PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id), photo_id INTEGER NOT NULL REFERENCES photos(id) ON DELETE CASCADE, reason TEXT NOT NULL, details TEXT DEFAULT '', status TEXT NOT NULL DEFAULT 'open', created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS notifications (id INTEGER PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, type TEXT NOT NULL, message TEXT NOT NULL, read_at TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS achievements (id INTEGER PRIMARY KEY, key TEXT UNIQUE NOT NULL, name TEXT NOT NULL, description TEXT NOT NULL, icon TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS user_achievements (user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, achievement_id INTEGER NOT NULL REFERENCES achievements(id) ON DELETE CASCADE, created_at TEXT NOT NULL, PRIMARY KEY(user_id, achievement_id));`)
db.exec(`CREATE TABLE IF NOT EXISTS password_resets (token TEXT PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, expires_at TEXT NOT NULL, used_at TEXT);`)
db.exec(`CREATE TABLE IF NOT EXISTS user_settings (user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE, theme TEXT NOT NULL DEFAULT 'light', public_profile INTEGER NOT NULL DEFAULT 1, show_city INTEGER NOT NULL DEFAULT 1, show_activity INTEGER NOT NULL DEFAULT 1, allow_ratings INTEGER NOT NULL DEFAULT 1);`)
db.exec(`CREATE TABLE IF NOT EXISTS ai_settings (id INTEGER PRIMARY KEY CHECK(id=1), mode TEXT NOT NULL DEFAULT 'test', endpoint TEXT NOT NULL DEFAULT '', model TEXT NOT NULL DEFAULT '', updated_at TEXT NOT NULL, api_key_ciphertext TEXT NOT NULL DEFAULT '');`)
try { db.exec("ALTER TABLE ai_settings ADD COLUMN api_key_ciphertext TEXT NOT NULL DEFAULT ''") } catch {}
try { db.exec("ALTER TABLE users ADD COLUMN avatar_url TEXT NOT NULL DEFAULT ''") } catch {}
try { db.exec("ALTER TABLE users ADD COLUMN banned_until TEXT") } catch {}
try { db.exec("ALTER TABLE users ADD COLUMN posting_restricted_until TEXT") } catch {}
if (!db.prepare('SELECT id FROM ai_settings WHERE id=1').get()) db.prepare('INSERT INTO ai_settings(id,mode,endpoint,model,updated_at) VALUES (1,?,?,?,?)').run('test','', '', new Date().toISOString())
for (const index of ['CREATE INDEX IF NOT EXISTS idx_photos_user_created ON photos(user_id,created_at)','CREATE INDEX IF NOT EXISTS idx_photos_place ON photos(place_id)','CREATE INDEX IF NOT EXISTS idx_likes_photo ON likes(photo_id)','CREATE INDEX IF NOT EXISTS idx_ratings_photo ON ratings(photo_id)','CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications(user_id,read_at)']) db.exec(index)
try { db.exec("ALTER TABLE photos ADD COLUMN category TEXT NOT NULL DEFAULT 'City'") } catch {}
try { db.exec("ALTER TABLE photos ADD COLUMN photo_type TEXT NOT NULL DEFAULT 'landscape'") } catch {}
if (db.prepare('SELECT COUNT(*) AS c FROM achievements').get().c === 0) { const add=db.prepare('INSERT INTO achievements(key,name,description,icon) VALUES (?,?,?,?)'); for (const a of [['first-shot','First Shot','Upload your first photo','📸'],['photographer','Photographer','Upload 10 photos','🗂️'],['high-score','High Score','Get an AI score above 90','⭐'],['top-shot','Top Shot','Earn 10 likes','🔥']]) add.run(...a) }
const now = () => new Date().toISOString()
const hash = (p) => crypto.createHash('sha256').update(p).digest('hex')
const hashPassword = (password) => { const salt=crypto.randomBytes(16); const derived=crypto.scryptSync(String(password),salt,64,{N:16384,r:8,p:1}); return `scrypt$${salt.toString('base64')}$${derived.toString('base64')}` }
const verifyPassword = (password, stored) => { try { const [,saltText,hashText]=String(stored).split('$'); if (!saltText || !hashText) return crypto.timingSafeEqual(Buffer.from(hash(password),'hex'),Buffer.from(stored,'hex')); const salt=Buffer.from(saltText,'base64'); const expected=Buffer.from(hashText,'base64'); const actual=crypto.scryptSync(String(password),salt,expected.length,{N:16384,r:8,p:1}); return expected.length===actual.length&&crypto.timingSafeEqual(actual,expected) } catch { return false } }
if (db.prepare('SELECT COUNT(*) AS c FROM users').get().c === 0) {
  const user = db.prepare('INSERT INTO users(username,email,password_hash,role,created_at) VALUES (?,?,?,?,?)').run('demo','demo@shotmap.local',hashPassword('demo123'),'user',now()).lastInsertRowid
  db.prepare('INSERT INTO users(username,email,password_hash,role,created_at) VALUES (?,?,?,?,?)').run('admin','admin@shotmap.local',hashPassword('admin123'),'admin',now())
  const places = [['Charles Bridge','Prague','Czech Republic',50.0865,14.4114,87],['Eiffel Tower','Paris','France',48.8584,2.2945,91],['Sagrada Família','Barcelona','Spain',41.4036,2.1744,89],['Colosseum','Rome','Italy',41.8902,12.4922,86]]
  const addPlace = db.prepare('INSERT INTO places(name,city,country,latitude,longitude,average_score) VALUES (?,?,?,?,?,?)')
  for (const p of places) addPlace.run(...p)
  const imgs = ['https://commons.wikimedia.org/wiki/Special:FilePath/Charles%20Bridge%20Prague%20in%20winter.jpg?width=1200','https://commons.wikimedia.org/wiki/Special:FilePath/Eiffel%20Tower%20at%20night.jpg?width=1200','https://commons.wikimedia.org/wiki/Special:FilePath/Sagrada%20Familia%202022.jpg?width=1200','https://commons.wikimedia.org/wiki/Special:FilePath/Colosseo%202020.jpg?width=1200']
  const addPhoto = db.prepare('INSERT INTO photos(user_id,place_id,image_url,title,created_at,ai_score,composition,lighting,sharpness,colors,visual_quality,community_score,likes) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)')
  for (let i=0;i<12;i++) { const score=90-(i%5); addPhoto.run(user,(i%4)+1,imgs[i%3],['Golden hour at the bridge','The quiet side of Paris','Blue hour in Barcelona'][i%3],now(),score,score+1,score-2,score,score+2,score,4.2+(i%8)/10,i*7) }
}
const worldPlaces = [
  ['Statue of Liberty','New York','United States',40.6892,-74.0445,90],
  ['Tokyo Skytree','Tokyo','Japan',35.7101,139.8107,88],
  ['Christ the Redeemer','Rio de Janeiro','Brazil',-22.9519,-43.2105,89],
  ['Sydney Opera House','Sydney','Australia',-33.8568,151.2153,91],
  ['Table Mountain','Cape Town','South Africa',-33.9628,18.4098,87],
  ['Pyramids of Giza','Giza','Egypt',29.9792,31.1342,90],
  ['Chichén Itzá','Yucatán','Mexico',20.6843,-88.5678,86],
  ['Taj Mahal','Agra','India',27.1751,78.0421,92]
]
const addWorldPlace = db.prepare('INSERT INTO places(name,city,country,latitude,longitude,average_score) SELECT ?,?,?,?,?,? WHERE NOT EXISTS (SELECT 1 FROM places WHERE name=? AND city=? AND country=?)')
for (const place of worldPlaces) addWorldPlace.run(...place,place[0],place[1],place[2])
if (worldPlaces.length) db.prepare("DELETE FROM places WHERE id NOT IN (SELECT MIN(id) FROM places GROUP BY name,city,country)").run()
db.prepare("UPDATE photos SET image_url=CASE place_id WHEN 1 THEN 'https://commons.wikimedia.org/wiki/Special:FilePath/Charles%20Bridge%20Prague%20in%20winter.jpg?width=1200' WHEN 2 THEN 'https://commons.wikimedia.org/wiki/Special:FilePath/Eiffel%20Tower%20at%20night.jpg?width=1200' WHEN 3 THEN 'https://commons.wikimedia.org/wiki/Special:FilePath/Sagrada%20Familia%202022.jpg?width=1200' WHEN 4 THEN 'https://commons.wikimedia.org/wiki/Special:FilePath/Colosseo%202020.jpg?width=1200' ELSE image_url END WHERE image_url LIKE 'https://images.unsplash.com/%'").run()
const pendingUpload=new Map()
const MAX_BODY_BYTES = 12_000_000
const securityHeaders = {'X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'strict-origin-when-cross-origin','Permissions-Policy':'camera=(), microphone=(), geolocation=()','Strict-Transport-Security':'max-age=31536000; includeSubDomains','Content-Security-Policy':"default-src 'self'; img-src 'self' data: https://*.tile.openstreetmap.org https://commons.wikimedia.org https://upload.wikimedia.org; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; script-src 'self'; connect-src 'self'"}
const json = (res, status, payload) => { res.writeHead(status, {'Content-Type':'application/json; charset=utf-8',...securityHeaders,'Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'GET,POST,PUT,DELETE,PATCH,OPTIONS'}); res.end(JSON.stringify(payload)) }
const body = async (req) => { let s=''; for await (const c of req) { s+=c; if (s.length > MAX_BODY_BYTES) throw new Error('Request is too large') }; try{return s ? JSON.parse(s) : {}}catch{throw new Error('Invalid JSON')} }
const route = (req) => new URL(req.url, `http://${req.headers.host}`)
const auth = (req) => { const token=(req.headers.authorization||'').replace(/^Bearer\s+/i,''); return token ? db.prepare('SELECT u.id,u.username,u.email,u.role FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=? AND s.expires_at>?').get(token,now()) : null }
const safe = (value, max=160) => String(value ?? '').trim().slice(0,max)
const validateImageData = (data) => { const match=String(data||'').match(/^data:image\/(jpeg|jpg|png|webp);base64,([A-Za-z0-9+/=]+)$/i); if(!match) { if(/^https:\/\//.test(data)) return {external:true}; throw new Error('Image must be JPG, PNG or WEBP') }; const ext=match[1].toLowerCase().replace('jpeg','jpg'); const bytes=Buffer.from(match[2],'base64'); const valid=(ext==='png'&&bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))||(ext==='jpg'&&bytes[0]===0xff&&bytes[1]===0xd8&&bytes[bytes.length-2]===0xff&&bytes[bytes.length-1]===0xd9)||(ext==='webp'&&bytes.subarray(0,4).toString()==='RIFF'&&bytes.subarray(8,12).toString()==='WEBP'); if(!valid) throw new Error('Image signature does not match declared format'); if(bytes.length>10*1024*1024) throw new Error('Image is too large'); return {ext,bytes} }
const saveImage = async (data) => { const checked=validateImageData(data); if(checked.external)return data; const name=`${Date.now()}-${crypto.randomBytes(5).toString('hex')}.${checked.ext}`; await writeFile(join(uploadsDir,name),checked.bytes); return `/uploads/${name}` }
const publicUrl = (req, value) => value
// Index existing local uploads; never download untrusted historical remote URLs.
for (const photo of db.prepare("SELECT id,image_url FROM photos WHERE id NOT IN (SELECT photo_id FROM image_fingerprints) AND image_url LIKE '/uploads/%'").all()) {
  if (!/^\/uploads\/[\w.-]+$/.test(photo.image_url)) continue
  try { const fp=await fingerprint(await readFile(join(uploadsDir,photo.image_url.slice(9)))); db.prepare('INSERT OR IGNORE INTO image_fingerprints VALUES (?,?,?,?)').run(photo.id,fp.sha256,fp.visualHash,fp.canonical) } catch { console.warn('Could not index local photo',photo.id) }
}
  const persistentKey = process.env.SHOTMAP_SETTINGS_SECRET || await (async()=>{const path=join(dataDir,'shotmap-settings-key');try{return (await readFile(path,'utf8')).trim()}catch{const generated=crypto.randomBytes(32).toString('hex');await writeFile(path,generated,{flag:'wx'}).catch(()=>{});return (await readFile(path,'utf8')).trim()}})()
const secretKey = crypto.createHash('sha256').update(persistentKey).digest()
const encryptSecret = value => { if (!value) return ''; const iv=crypto.randomBytes(12), cipher=crypto.createCipheriv('aes-256-gcm',secretKey,iv); const encrypted=Buffer.concat([cipher.update(String(value),'utf8'),cipher.final()]); return `${iv.toString('base64')}.${cipher.getAuthTag().toString('base64')}.${encrypted.toString('base64')}` }
const decryptSecret = value => { try { if (!value) return ''; const [iv,tag,data]=String(value).split('.'); const decipher=crypto.createDecipheriv('aes-256-gcm',secretKey,Buffer.from(iv,'base64')); decipher.setAuthTag(Buffer.from(tag,'base64')); return Buffer.concat([decipher.update(Buffer.from(data,'base64')),decipher.final()]).toString('utf8') } catch { return '' } }
const boundedMetric = value => Math.max(0, Math.min(100, Math.round(Number(value) || 0)))
async function processImage(image, meta = {}) {
  const settings = db.prepare('SELECT mode,endpoint,model,api_key_ciphertext FROM ai_settings WHERE id=1').get() || {mode:'test'}
  if (settings.mode !== 'api') return analyze(image)
  let input=image
  if (input.startsWith('/uploads/')) {
    if (!/^\/uploads\/[\w.-]+$/.test(input)) throw new Error('Invalid image path')
    const bytes=await readFile(join(uploadsDir,input.slice(9)))
    input=`data:image/${extname(input).slice(1).replace('jpg','jpeg')};base64,${bytes.toString('base64')}`
  }
  try { return {...await requestAnalysis({...settings,apiKey:decryptSecret(settings.api_key_ciphertext)||process.env.AI_API_KEY||'',image:input}),provider:'api'} } catch (providerError) { console.warn('[ai] provider failed, local fallback used:',providerError.message); return {...analyze(input),provider:'local-fallback',providerError:providerError.message} }
  // Clarify upstream failures: the local model never claims to be the provider.
 }
async function api(req,res,url) {
  const p=url.pathname
  try {
    if (req.method==='OPTIONS') return json(res,204,{})
    if (req.method==='GET' && p==='/api/health') return json(res,200,{ok:true,db:'sqlite'})
    if (req.method==='GET' && p==='/api/geocode') { const q=safe(url.searchParams.get('q'),120); const limit=Math.min(12,Math.max(1,Number(url.searchParams.get('limit')||8))); if(q.length<2) return json(res,200,{results:[]}); const places=db.prepare('SELECT id,name,city,country,latitude,longitude FROM places').all(); return json(res,200,{results: await searchPlaces({text:q,places,limit})}) }
    if (req.method==='POST' && p==='/api/photos/guess-location') { const u=auth(req); if(!u) return json(res,401,{error:'Login required'}); const b=await body(req); const checked=validateImageData(b.image); if(checked.external) return json(res,400,{error:'Upload the original file, not an internet link'}); const s=db.prepare('SELECT mode,endpoint,model,api_key_ciphertext FROM ai_settings WHERE id=1').get(); if(!s||s.mode!=='api'||!s.endpoint) return json(res,200,{guess:null,reason:'AI provider is not configured'}); let guess=null; try { guess=await guessLocationName({endpoint:s.endpoint,model:s.model,apiKey:decryptSecret(s.api_key_ciphertext)||'',image:typeof b.image==='string'?b.image:`data:image/jpeg;base64,${Buffer.from(b.image).toString('base64')}`}) } catch(e) { console.warn('[ai] location guess failed:',e.message); return json(res,200,{guess:null,reason:e.message}) } return json(res,200,{guess}) }
    if (req.method==='GET' && p==='/api/places') { const q=safe(url.searchParams.get('q'),80); const min=Number(url.searchParams.get('min_score')||0); const page=Math.max(1,Number(url.searchParams.get('page')||1)), limit=Math.min(50,Math.max(1,Number(url.searchParams.get('limit')||20))), offset=(page-1)*limit; const where=`WHERE p.average_score>=? AND (p.name LIKE ? OR p.city LIKE ? OR p.country LIKE ?)`; const params=[min,`%${q}%`,`%${q}%`,`%${q}%`]; const total=db.prepare(`SELECT COUNT(*) c FROM places p ${where}`).get(...params).c; const places=db.prepare(`SELECT p.*, COUNT(ph.id) photos FROM places p LEFT JOIN photos ph ON ph.place_id=p.id ${where} GROUP BY p.id ORDER BY p.average_score DESC LIMIT ? OFFSET ?`).all(...params,limit,offset); return json(res,200,{places,pagination:{page,limit,total,pages:Math.ceil(total/limit)}}) }
    if (req.method==='GET' && p==='/api/photos') { const sort=['ai_score','likes','created_at'].includes(url.searchParams.get('sort')) ? url.searchParams.get('sort') : 'created_at'; const category=safe(url.searchParams.get('category'),30); const photoType=safe(url.searchParams.get('type'),30); const radiusKm=Math.min(20000,Math.max(0,Number(url.searchParams.get('radius_km')||0))); const centerLat=Number(url.searchParams.get('lat')); const centerLng=Number(url.searchParams.get('lng')); const hasCenter=Number.isFinite(centerLat)&&Number.isFinite(centerLng)&&radiusKm>0; const min=Number(url.searchParams.get('min_score')||0); const page=Math.max(1,Number(url.searchParams.get('page')||1)), limit=Math.min(50,Math.max(1,Number(url.searchParams.get('limit')||20))), offset=(page-1)*limit; const distanceClause=hasCenter?' AND p.latitude IS NOT NULL AND p.longitude IS NOT NULL AND ((p.latitude-?)*(p.latitude-?)+(p.longitude-?)*(p.longitude-?)) <= ?':''; const where="WHERE ph.ai_score>=? AND (?='' OR ph.category=?) AND (?='' OR ph.photo_type=?)"+distanceClause; const params=hasCenter?[min,category,category,photoType,photoType,centerLat,centerLat,centerLng,centerLng,(radiusKm/111)**2]:[min,category,category,photoType,photoType]; const total=db.prepare(`SELECT COUNT(*) c FROM photos ph LEFT JOIN places p ON p.id=ph.place_id ${where}`).get(...params).c; const photos=db.prepare(`SELECT ph.*,u.username, p.name place_name FROM photos ph JOIN users u ON u.id=ph.user_id LEFT JOIN places p ON p.id=ph.place_id ${where} ORDER BY ${sort} DESC LIMIT ? OFFSET ?`).all(...params,limit,offset).map(x=>({...x,image_url:publicUrl(req,x.image_url)})); return json(res,200,{photos,pagination:{page,limit,total,pages:Math.ceil(total/limit)}}) }
    if (req.method==='GET' && p==='/api/me') { const u=auth(req); return u ? json(res,200,{user:u}) : json(res,401,{error:'Authentication required'}) }
    if (req.method==='GET' && p.startsWith('/api/places/')) { const id=Number(p.split('/').pop()); const place=db.prepare('SELECT * FROM places WHERE id=?').get(id); if(!place)return json(res,404,{error:'Place not found'}); return json(res,200,{place,photos:db.prepare('SELECT ph.*,u.username FROM photos ph JOIN users u ON u.id=ph.user_id WHERE place_id=? ORDER BY ai_score DESC').all(id).map(x=>({...x,image_url:publicUrl(req,x.image_url)}))}) }
    if (req.method==='GET' && p.match(/^\/api\/photos\/\d+$/)) { const id=Number(p.split('/').pop()); const photo=db.prepare('SELECT ph.*,u.username,p.name place_name,p.city,p.country,p.latitude,p.longitude FROM photos ph JOIN users u ON u.id=ph.user_id LEFT JOIN places p ON p.id=ph.place_id WHERE ph.id=?').get(id); if(!photo)return json(res,404,{error:'Photo not found'}); db.prepare('UPDATE photos SET views=views+1 WHERE id=?').run(id); return json(res,200,{photo:{...photo,image_url:publicUrl(req,photo.image_url)}}) }
    if (req.method==='GET' && p==='/api/leaderboard') { const users=db.prepare(`SELECT u.id,u.username,u.avatar_url,COUNT(DISTINCT ph.id) photos,COALESCE(ROUND(AVG(ph.ai_score),0),0) average_score,COALESCE(SUM(ph.likes),0) likes FROM users u LEFT JOIN photos ph ON ph.user_id=u.id GROUP BY u.id ORDER BY average_score DESC, likes DESC LIMIT 50`).all(); return json(res,200,{users}) }
    if (req.method==='GET' && p==='/api/recommendations') { const u=auth(req); const excluded=u?db.prepare('SELECT place_id FROM place_favorites WHERE user_id=?').all(u.id).map(x=>x.place_id):[]; const query=`SELECT p.*,COUNT(ph.id) photos FROM places p LEFT JOIN photos ph ON ph.place_id=p.id ${excluded.length?'WHERE p.id NOT IN ('+excluded.map(()=>'?').join(',')+')':''} GROUP BY p.id ORDER BY p.average_score DESC,photos DESC LIMIT 6`; return json(res,200,{places:db.prepare(query).all(...excluded)}) }
    if (req.method==='GET' && p==='/api/admin/photos') { const u=auth(req); if(!u||u.role!=='admin')return json(res,403,{error:'Admin access required'}); return json(res,200,{photos:db.prepare('SELECT ph.id,ph.title,ph.image_url,ph.ai_score,ph.composition,ph.lighting,ph.sharpness,ph.colors,ph.visual_quality,ph.category,ph.likes,ph.views,ph.created_at,u.username,p.name place_name,ph.error,ph.ai_model FROM photos ph JOIN users u ON u.id=ph.user_id LEFT JOIN places p ON p.id=ph.place_id ORDER BY ph.created_at DESC LIMIT 100').all().map(x=>({...x,image_url:publicUrl(req,x.image_url)}))}) }
    if (req.method==='POST' && p.match(/^\/api\/admin\/photos\/\d+\/rescore$/)) { const u=auth(req); if(!u||u.role!=='admin')return json(res,403,{error:'Admin access required'}); const id=Number(p.split('/')[4]); const photo=db.prepare('SELECT * FROM photos WHERE id=?').get(id); if(!photo)return json(res,404,{error:'Photo not found'}); const metrics=await processImage(photo.image_url,{title:photo.title,category:photo.category}); db.prepare('UPDATE photos SET ai_score=?,composition=?,lighting=?,sharpness=?,colors=?,visual_quality=?,ai_model=?,error=? WHERE id=?').run(metrics.overallScore,metrics.composition,metrics.lighting,metrics.sharpness,metrics.colors,metrics.visualQuality,metrics.provider||'test',metrics.providerError||null,id); return json(res,200,{ok:true,metrics}) }
    if (req.method==='GET' && p==='/api/admin/places') { const u=auth(req); if(!u||u.role!=='admin')return json(res,403,{error:'Admin access required'}); return json(res,200,{places:db.prepare('SELECT p.*,COUNT(ph.id) photos FROM places p LEFT JOIN photos ph ON ph.place_id=p.id GROUP BY p.id ORDER BY p.id DESC').all()}) }
    if (req.method==='POST' && p==='/api/admin/places') { const u=auth(req); if(!u||u.role!=='admin')return json(res,403,{error:'Admin access required'}); const b=await body(req); const name=safe(b.name,120),city=safe(b.city,80),country=safe(b.country,80),lat=Number(b.latitude),lng=Number(b.longitude),score=boundedMetric(b.average_score||88); if(!name||!city||!country||!Number.isFinite(lat)||!Number.isFinite(lng))return json(res,400,{error:'Enter name, city, country and valid coordinates'}); const id=db.prepare('INSERT INTO places(name,city,country,latitude,longitude,average_score) VALUES (?,?,?,?,?,?)').run(name,city,country,lat,lng,score).lastInsertRowid; return json(res,201,{place:db.prepare('SELECT * FROM places WHERE id=?').get(id)}) }
    if (req.method==='DELETE' && p.match(/^\/api\/admin\/places\/\d+$/)) { const u=auth(req); if(!u||u.role!=='admin')return json(res,403,{error:'Admin access required'}); const id=Number(p.split('/').pop()); db.prepare('UPDATE photos SET place_id=NULL WHERE place_id=?').run(id); db.prepare('DELETE FROM places WHERE id=?').run(id); return json(res,200,{ok:true}) }
    if (req.method==='POST' && p==='/api/admin/broadcast') { const u=auth(req); if(!u||u.role!=='admin')return json(res,403,{error:'Admin access required'}); const b=await body(req); const msg=safe(b.message,300); if(!msg)return json(res,400,{error:'Enter a broadcast message'}); const allUsers=db.prepare('SELECT id FROM users').all(); const ins=db.prepare('INSERT INTO notifications(user_id,type,message,created_at) VALUES (?,?,?,?)'); for(const target of allUsers) ins.run(target.id,'system',`📣 Admin: ${msg}`,now()); return json(res,200,{ok:true,sent:allUsers.length}) }
    if (req.method==='GET' && p==='/api/admin/ai-settings') { const u=auth(req); if(!u||u.role!=='admin')return json(res,403,{error:'AI settings require admin'}); const s=db.prepare('SELECT mode,endpoint,model,updated_at,CASE WHEN api_key_ciphertext=\'\' THEN 0 ELSE 1 END api_key_set FROM ai_settings WHERE id=1').get(); return json(res,200,{settings:s}) }
    if (req.method==='PUT' && p==='/api/admin/ai-settings') { const u=auth(req); if(!u||u.role!=='admin')return json(res,403,{error:'AI settings require admin'}); const b=await body(req); const mode=['test','api'].includes(b.mode)?b.mode:'test'; const endpoint=safe(b.endpoint,500); const model=safe(b.model,100); const suppliedKey=b.api_key===undefined?null:String(b.api_key).trim(); if(mode==='api'&&!/^https:\/\//i.test(endpoint))return json(res,400,{error:'AI endpoint must use HTTPS'}); if(suppliedKey!==null&&suppliedKey.length>2000)return json(res,400,{error:'API key is too long'}); const current=db.prepare('SELECT api_key_ciphertext FROM ai_settings WHERE id=1').get(); const key=suppliedKey===null||suppliedKey===''?current.api_key_ciphertext:encryptSecret(suppliedKey); db.prepare('UPDATE ai_settings SET mode=?,endpoint=?,model=?,api_key_ciphertext=?,updated_at=? WHERE id=1').run(mode,endpoint,model,key,now()); return json(res,200,{settings:db.prepare('SELECT mode,endpoint,model,updated_at,CASE WHEN api_key_ciphertext=\'\' THEN 0 ELSE 1 END api_key_set FROM ai_settings WHERE id=1').get()}) }
    if (req.method==='GET' && p==='/api/admin/overview') { const u=auth(req); if(!u||u.role!=='admin')return json(res,403,{error:'Admin access required'}); if(db.prepare('SELECT COUNT(*) c FROM reports').get().c===0){const uRow=db.prepare('SELECT id FROM users ORDER BY id LIMIT 1').get();const phRows=db.prepare('SELECT id FROM photos ORDER BY id LIMIT 3').all();if(uRow&&phRows.length){const addRep=db.prepare('INSERT INTO reports(user_id,photo_id,reason,details,status,created_at) VALUES (?,?,?,?,?,?)');addRep.run(uRow.id,phRows[0].id,'wrong_location','GPS pin appears 400m east of the bridge tower','open',now());if(phRows[1])addRep.run(uRow.id,phRows[1].id,'copyright','Watermark cropped in bottom corner','open',now());if(phRows[2])addRep.run(uRow.id,phRows[2].id,'spam','Duplicate winter series upload','reviewed',now())}} const stats={users:db.prepare('SELECT COUNT(*) c FROM users').get().c,photos:db.prepare('SELECT COUNT(*) c FROM photos').get().c,places:db.prepare('SELECT COUNT(*) c FROM places').get().c,reports:db.prepare("SELECT COUNT(*) c FROM reports WHERE status='open'").get().c,avg_ai:db.prepare('SELECT COALESCE(ROUND(AVG(ai_score),1),0) c FROM photos').get().c,total_likes:db.prepare('SELECT COALESCE(SUM(likes),0) c FROM photos').get().c,total_views:db.prepare('SELECT COALESCE(SUM(views),0) c FROM photos').get().c,categories:db.prepare('SELECT category,COUNT(*) count,ROUND(AVG(ai_score),1) avg_score FROM photos GROUP BY category ORDER BY count DESC').all()}; return json(res,200,{stats,settings:db.prepare('SELECT mode,endpoint,model,updated_at,CASE WHEN api_key_ciphertext=\'\' THEN 0 ELSE 1 END api_key_set FROM ai_settings WHERE id=1').get()}) }
    if (req.method==='GET' && p==='/api/stats') { return json(res,200,{stats:{users:db.prepare('SELECT COUNT(*) c FROM users').get().c,photos:db.prepare('SELECT COUNT(*) c FROM photos').get().c,places:db.prepare('SELECT COUNT(*) c FROM places').get().c,analyses:db.prepare('SELECT COUNT(*) c FROM photos WHERE ai_score IS NOT NULL').get().c}}) }
    if (req.method==='GET' && p==='/api/achievements') return json(res,200,{achievements:db.prepare('SELECT * FROM achievements ORDER BY id').all()})
    if (req.method==='GET' && p==='/api/notifications') { const u=auth(req); if(!u)return json(res,401,{error:'Login required'}); return json(res,200,{notifications:db.prepare('SELECT * FROM notifications WHERE user_id=? ORDER BY created_at DESC LIMIT 50').all(u.id)}) }
    if (req.method==='POST' && p==='/api/notifications/read') { const u=auth(req); if(!u)return json(res,401,{error:'Login required'}); db.prepare('UPDATE notifications SET read_at=? WHERE user_id=?').run(now(),u.id); return json(res,200,{ok:true}) }
    // Public profile of any user. Query param id = someone else's profile;
    // no id = the caller's own profile (email included only then).
    if (req.method==='GET' && p==='/api/profile') {
      const caller = auth(req)
      const id = Number(url.searchParams.get('id')) || caller?.id
      if(!id) return json(res,401,{error:'Login required'})
      const user = db.prepare('SELECT id,username,email,role,created_at,avatar_url FROM users WHERE id=?').get(id)
      if(!user) return json(res,404,{error:'User not found'})
      const isSelf = caller?.id === id
      const settings = db.prepare('SELECT public_profile FROM user_settings WHERE user_id=?').get(id)
      const isPublic = settings?.public_profile ?? 1
      if (!isSelf && !isPublic) return json(res,403,{error:'This profile is private'})
      const photos = db.prepare('SELECT id,user_id,place_id,title,description,image_url,ai_score,category,created_at,likes FROM photos WHERE user_id=? ORDER BY ai_score DESC').all(id).map(x=>({...x,image_url:publicUrl(req,x.image_url)}))
      const favorites = db.prepare('SELECT ph.* FROM photos ph JOIN favorites f ON f.photo_id=ph.id WHERE f.user_id=? ORDER BY f.created_at DESC').all(id).map(x=>({...x,image_url:publicUrl(req,x.image_url)}))
      const savedPlaces = db.prepare('SELECT p.* FROM places p JOIN place_favorites f ON f.place_id=p.id WHERE f.user_id=? ORDER BY f.created_at DESC').all(id)
      const stats = (()=>{const s=db.prepare('SELECT COUNT(*) photos,COALESCE(SUM(likes),0) likes,COALESCE(ROUND(AVG(ai_score),1),0) average_score,COUNT(DISTINCT place_id) places FROM photos WHERE user_id=?').get(id);const achievements=db.prepare('SELECT COUNT(*) c FROM user_achievements WHERE user_id=?').get(id).c;const xp=s.photos*20+s.likes*2+achievements*100;return {...s,achievements,level:Math.floor(xp/250)+1,xp,xp_for_next:250-(xp%250)}})()
      const placeRows = db.prepare('SELECT DISTINCT p.* FROM places p JOIN photos ph ON ph.place_id=p.id WHERE ph.user_id=?').all(id)
      return json(res,200,{user:{id:user.id,username:user.username,role:user.role,created_at:user.created_at,avatar_url:publicUrl(req,user.avatar_url),...(isSelf?{email:user.email}:{})},photos,favorites,saved_places:savedPlaces,place_ids:placeRows.map(p=>p.id),places:placeRows,statistics:stats,achievements:db.prepare('SELECT a.* FROM achievements a JOIN user_achievements ua ON ua.achievement_id=a.id WHERE ua.user_id=?').all(id)})
    }
    if (req.method==='GET' && p==='/api/me/statistics') { const u=auth(req); if(!u)return json(res,401,{error:'Login required'}); const s=db.prepare('SELECT COUNT(*) photos,COALESCE(SUM(likes),0) likes,COALESCE(ROUND(AVG(ai_score),1),0) average_ai,COALESCE(ROUND(AVG(composition),0),0) composition,COALESCE(ROUND(AVG(lighting),0),0) lighting,COALESCE(ROUND(AVG(sharpness),0),0) sharpness,COALESCE(ROUND(AVG(colors),0),0) colors,COALESCE(ROUND(AVG(visual_quality),0),0) visual_quality,COUNT(DISTINCT place_id) places FROM photos WHERE user_id=?').get(u.id); const achievements=db.prepare('SELECT COUNT(*) c FROM user_achievements WHERE user_id=?').get(u.id).c; const skills={composition:s.composition,lighting:s.lighting,sharpness:s.sharpness,colors:s.colors,visual_quality:s.visual_quality}; const strongest=Object.entries(skills).sort((a,b)=>b[1]-a[1])[0][0]; const weakest=Object.entries(skills).sort((a,b)=>a[1]-b[1])[0][0]; const xp=s.photos*20+s.likes*2+achievements*100; return json(res,200,{statistics:{...s,achievements,xp,level:Math.floor(xp/250)+1,strongest,weakest}}) }
    if (req.method==='GET' && p==='/api/me/photos') { const u=auth(req); if(!u)return json(res,401,{error:'Login required'}); const allowed=['created_at','ai_score','likes','community_score']; const sort=allowed.includes(url.searchParams.get('sort'))?url.searchParams.get('sort'):'created_at'; const min=Math.max(0,Math.min(100,Number(url.searchParams.get('min_score')||0))); const photos=db.prepare(`SELECT ph.*,p.name place_name,p.city,p.country FROM photos ph LEFT JOIN places p ON p.id=ph.place_id WHERE ph.user_id=? AND ph.ai_score>=? ORDER BY ${sort} DESC LIMIT 100`).all(u.id,min).map(x=>({...x,image_url:publicUrl(req,x.image_url)})); return json(res,200,{photos}) }
    if (req.method==='GET' && p==='/api/me/places') { const u=auth(req); if(!u)return json(res,401,{error:'Login required'}); return json(res,200,{places:db.prepare('SELECT p.*,COUNT(ph.id) photos,ROUND(AVG(ph.ai_score),0) average_ai FROM places p JOIN photos ph ON ph.place_id=p.id WHERE ph.user_id=? GROUP BY p.id ORDER BY photos DESC').all(u.id)}) }
    if (req.method==='GET' && p==='/api/me/notifications') { const u=auth(req); if(!u)return json(res,401,{error:'Login required'}); return json(res,200,{notifications:db.prepare('SELECT * FROM notifications WHERE user_id=? ORDER BY created_at DESC LIMIT 100').all(u.id)}) }
    if (req.method==='PATCH' && p.match(/^\/api\/notifications\/\d+\/read$/)) { const u=auth(req); if(!u)return json(res,401,{error:'Login required'}); const id=Number(p.split('/')[3]); db.prepare('UPDATE notifications SET read_at=? WHERE id=? AND user_id=?').run(now(),id,u.id); return json(res,200,{ok:true}) }
    if (req.method==='PATCH' && p.match(/^\/api\/photos\/\d+$/)) { const u=auth(req); if(!u)return json(res,401,{error:'Login required'}); const id=Number(p.split('/').pop()); const b=await body(req); const photo=db.prepare('SELECT id FROM photos WHERE id=? AND user_id=?').get(id,u.id); if(!photo)return json(res,404,{error:'Photo not found'}); const category=['Landscape','Architecture','Nature','People','City','Night'].includes(b.category)?b.category:null; db.prepare('UPDATE photos SET title=COALESCE(NULLIF(?,\'\'),title),description=COALESCE(?,description),category=COALESCE(?,category),taken_at=COALESCE(?,taken_at),place_id=COALESCE(?,place_id) WHERE id=? AND user_id=?').run(safe(b.title,160),safe(b.description,1000),category,safe(b.taken_at,40),Number(b.place_id)||null,id,u.id); return json(res,200,{ok:true}) }
    if (req.method==='DELETE' && p.match(/^\/api\/photos\/\d+$/)) { const u=auth(req); if(!u)return json(res,401,{error:'Login required'}); const id=Number(p.split('/').pop()); const photo=db.prepare('SELECT image_url FROM photos WHERE id=? AND user_id=?').get(id,u.id); if(!photo)return json(res,404,{error:'Photo not found'}); db.prepare('DELETE FROM photos WHERE id=? AND user_id=?').run(id,u.id); db.prepare('DELETE FROM image_fingerprints WHERE photo_id=?').run(id); if(photo.image_url?.startsWith('/uploads/'))await unlink(join(uploadsDir,photo.image_url.slice('/uploads/'.length))).catch(()=>{}); return json(res,200,{ok:true}) }
    if (req.method==='PUT' && p==='/api/profile') { const u=auth(req); if(!u)return json(res,401,{error:'Login required'}); const b=await body(req); const username=safe(b.username,32); if(username&&!/^[a-zA-Z0-9_]{3,32}$/.test(username))return json(res,400,{error:'Invalid username'}); const current=db.prepare('SELECT avatar_url FROM users WHERE id=?').get(u.id); let avatar=current.avatar_url; if(b.avatar_url!==undefined && b.avatar_url!==current.avatar_url){if(String(b.avatar_url).startsWith('data:image/'))avatar=await saveImage(b.avatar_url);else if(b.avatar_url==='')avatar='';else return json(res,400,{error:'Upload an image file for your avatar'})} db.prepare('UPDATE users SET username=COALESCE(NULLIF(?,\'\'),username),avatar_url=? WHERE id=?').run(username,avatar,u.id); const user=db.prepare('SELECT id,username,email,role,created_at,avatar_url FROM users WHERE id=?').get(u.id); return json(res,200,{user}) }
    if (req.method==='GET' && p==='/api/me/settings') { const u=auth(req); if(!u)return json(res,401,{error:'Login required'}); const s=db.prepare('SELECT theme,public_profile,show_city,show_activity,allow_ratings FROM user_settings WHERE user_id=?').get(u.id) || {theme:'light',public_profile:1,show_city:1,show_activity:1,allow_ratings:1}; return json(res,200,{settings:s}) }
    if (req.method==='PUT' && p==='/api/me/settings') { const u=auth(req); if(!u)return json(res,401,{error:'Login required'}); const b=await body(req); const theme=['light','dark'].includes(b.theme)?b.theme:'light'; db.prepare('INSERT INTO user_settings(user_id,theme,public_profile,show_city,show_activity,allow_ratings) VALUES (?,?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET theme=excluded.theme,public_profile=excluded.public_profile,show_city=excluded.show_city,show_activity=excluded.show_activity,allow_ratings=excluded.allow_ratings').run(u.id,theme,b.public_profile?1:0,b.show_city?1:0,b.show_activity?1:0,b.allow_ratings?1:0); return json(res,200,{settings:db.prepare('SELECT * FROM user_settings WHERE user_id=?').get(u.id)}) }
    if (req.method==='POST' && p==='/api/reports') { const u=auth(req); if(!u)return json(res,401,{error:'Login required'}); const b=await body(req); if(!['spam','inappropriate','copyright','wrong_location','other'].includes(b.reason))return json(res,400,{error:'Invalid report reason'}); const id=db.prepare('INSERT INTO reports(user_id,photo_id,reason,details,created_at) VALUES (?,?,?,?,?)').run(u.id,Number(b.photo_id),b.reason,safe(b.details,500),now()).lastInsertRowid; return json(res,201,{report:{id,status:'open'}}) }
    if (req.method==='GET' && p==='/api/admin/reports') { const u=auth(req); if(!u||u.role!=='admin')return json(res,403,{error:'Admin access required'}); return json(res,200,{reports:db.prepare('SELECT r.*,u.username,ph.title,ph.image_url,ph.ai_score FROM reports r JOIN users u ON u.id=r.user_id JOIN photos ph ON ph.id=r.photo_id ORDER BY r.created_at DESC').all().map(x=>({...x,image_url:publicUrl(req,x.image_url)}))}) }
    if (req.method==='GET' && p==='/api/admin/users') { const u=auth(req); if(!u||u.role!=='admin')return json(res,403,{error:'Admin access required'}); return json(res,200,{users:db.prepare('SELECT u.id,u.username,u.email,u.role,u.created_at,u.avatar_url,u.banned_until,u.posting_restricted_until,COUNT(ph.id) photos,COALESCE(ROUND(AVG(ph.ai_score),0),0) avg_score FROM users u LEFT JOIN photos ph ON ph.user_id=u.id GROUP BY u.id ORDER BY u.created_at DESC').all().map(x=>({...x,avatar_url:publicUrl(req,x.avatar_url)}))}) }
    if (req.method==='PATCH' && p.match(/^\/api\/admin\/users\/\d+$/)) { const u=auth(req); if(!u||u.role!=='admin')return json(res,403,{error:'Admin access required'}); const id=Number(p.split('/').pop()); const target=db.prepare('SELECT id,role FROM users WHERE id=?').get(id); if(!target)return json(res,404,{error:'User not found'}); const b=await body(req); if(target.role==='admin'&&id!==u.id&&b?.action!=='unban'&&b?.action!=='demote')return json(res,400,{error:'Cannot moderate another admin'}); const mode=['ban','restrict','unban','unrestrict','promote','demote'].includes(b.action)?b.action:''; if(!mode)return json(res,400,{error:'Invalid user action'}); const until=(mode==='ban'||mode==='restrict') ? new Date(Date.now()+Math.min(365,Math.max(1,Number(b.days)||7))*86400000).toISOString() : null; if(mode==='ban')db.prepare('UPDATE users SET banned_until=? WHERE id=?').run(until,id); if(mode==='unban')db.prepare('UPDATE users SET banned_until=NULL,posting_restricted_until=NULL WHERE id=?').run(id); if(mode==='restrict'||mode==='unrestrict')db.prepare('UPDATE users SET posting_restricted_until=? WHERE id=?').run(mode==='restrict'?until:null,id); if(mode==='promote')db.prepare("UPDATE users SET role='admin' WHERE id=?").run(id); if(mode==='demote'&&id!==u.id)db.prepare("UPDATE users SET role='user' WHERE id=?").run(id); return json(res,200,{ok:true,user:db.prepare('SELECT id,username,role,banned_until,posting_restricted_until FROM users WHERE id=?').get(id)}) }
    if (req.method==='DELETE' && p.match(/^\/api\/admin\/users\/\d+$/)) { const u=auth(req); if(!u||u.role!=='admin')return json(res,403,{error:'Admin access required'}); const id=Number(p.split('/').pop()); const target=db.prepare('SELECT id,role FROM users WHERE id=?').get(id); if(!target)return json(res,404,{error:'User not found'}); if(target.role==='admin')return json(res,400,{error:'Cannot delete an admin'}); db.prepare('DELETE FROM users WHERE id=?').run(id); return json(res,200,{ok:true}) }
    if (req.method==='DELETE' && p.match(/^\/api\/admin\/photos\/\d+$/)) { const u=auth(req); if(!u||u.role!=='admin')return json(res,403,{error:'Admin access required'}); const id=Number(p.split('/').pop()); const photo=db.prepare('SELECT image_url FROM photos WHERE id=?').get(id); if(!photo)return json(res,404,{error:'Photo not found'}); db.prepare('DELETE FROM photos WHERE id=?').run(id); if(photo.image_url?.startsWith('/uploads/')) await unlink(join(uploadsDir,photo.image_url.slice('/uploads/'.length))).catch(()=>{}); return json(res,200,{ok:true}) }
    if (req.method==='PATCH' && p.match(/^\/api\/admin\/reports\/\d+$/)) { const u=auth(req); if(!u||u.role!=='admin')return json(res,403,{error:'Admin access required'}); const id=Number(p.split('/').pop()); const b=await body(req); if(!['open','reviewed','resolved','rejected'].includes(b.status))return json(res,400,{error:'Invalid status'}); db.prepare('UPDATE reports SET status=? WHERE id=?').run(b.status,id); return json(res,200,{ok:true}) }
    if (req.method==='POST' && p==='/api/auth/register') { const b=await body(req); const username=safe(b.username,32),email=safe(b.email,200).toLowerCase(); if(!/^[a-zA-Z0-9_]{3,32}$/.test(username)||!/^\S+@\S+\.\S+$/.test(email)||String(b.password||'').length<6) return json(res,400,{error:'Enter a valid username, email and password (6+ chars)'}); const id=db.prepare('INSERT INTO users(username,email,password_hash,created_at) VALUES (?,?,?,?)').run(username,email,hashPassword(b.password),now()).lastInsertRowid; const token=crypto.randomBytes(32).toString('hex'); db.prepare('INSERT INTO sessions VALUES (?,?,?)').run(token,id,new Date(Date.now()+7*86400000).toISOString()); return json(res,201,{user:{id,username,email,role:'user'},token}) }
    if (req.method==='POST' && p==='/api/auth/login') { const b=await body(req), email=safe(b.email,200); const u=db.prepare('SELECT id,username,email,role,banned_until,password_hash FROM users WHERE email=?').get(email); if(!u||!verifyPassword(String(b.password||''),u.password_hash))return json(res,401,{error:'Invalid credentials'}); if(u.banned_until&&u.banned_until>now())return json(res,403,{error:'Account banned until '+u.banned_until}); const token=crypto.randomBytes(32).toString('hex'); db.prepare('INSERT INTO sessions VALUES (?,?,?)').run(token,u.id,new Date(Date.now()+7*86400000).toISOString()); return json(res,200,{user:{id:u.id,username:u.username,email:u.email,role:u.role,banned_until:u.banned_until},token}) }
    if (req.method==='POST' && p==='/api/auth/logout') { const token=(req.headers.authorization||'').replace(/^Bearer\s+/i,''); db.prepare('DELETE FROM sessions WHERE token=?').run(token); return json(res,200,{ok:true}) }
    if (req.method==='POST' && p==='/api/auth/forgot-password') { const b=await body(req), email=safe(b.email,200).toLowerCase(), u=db.prepare('SELECT id FROM users WHERE email=?').get(email); if(u){const token=crypto.randomBytes(24).toString('hex'); db.prepare('INSERT INTO password_resets VALUES (?,?,?,NULL)').run(hash(token),u.id,new Date(Date.now()+30*60*1000).toISOString())} return json(res,200,{ok:true,message:'If this email exists, reset instructions will be sent'}) }
    if (req.method==='POST' && p==='/api/auth/reset-password') { const b=await body(req); if(!b.token||String(b.password||'').length<6)return json(res,400,{error:'Token and password (6+ chars) are required'}); const candidates=db.prepare('SELECT * FROM password_resets WHERE used_at IS NULL AND expires_at>?').all(now()); const r=candidates.find(x=>verifyPassword(String(b.token),x.token)); if(!r)return json(res,400,{error:'Invalid or expired reset token'}); db.prepare('UPDATE users SET password_hash=? WHERE id=?').run(hashPassword(b.password),r.user_id); db.prepare('UPDATE password_resets SET used_at=? WHERE token=?').run(now(),r.token); db.prepare('DELETE FROM sessions WHERE user_id=?').run(r.user_id); return json(res,200,{ok:true}) }
    if (req.method==='POST' && p==='/api/photos') { const u=auth(req); if(!u)return json(res,401,{error:'Login required to upload'}); const fullUser=db.prepare('SELECT banned_until,posting_restricted_until FROM users WHERE id=?').get(u.id); if(fullUser.banned_until&&fullUser.banned_until>now())return json(res,403,{error:'Your account is banned until '+fullUser.banned_until}); if(fullUser.posting_restricted_until&&fullUser.posting_restricted_until>now())return json(res,403,{error:'Photo publishing is restricted until '+fullUser.posting_restricted_until}); const b=await body(req); if(!b.image_url)return json(res,400,{error:'Image is required'}); let place=db.prepare('SELECT id FROM places WHERE id=?').get(Number(b.place_id)); if(!place&&Number.isFinite(Number(b.latitude))&&Number.isFinite(Number(b.longitude))&&b.place_name){const name=safe(b.place_name,120),city=safe(b.city,80),country=safe(b.country,80);const existing=db.prepare('SELECT id FROM places WHERE ABS(latitude-?)<0.001 AND ABS(longitude-?)<0.001').get(Number(b.latitude),Number(b.longitude));if(existing)place=existing;else place={id:db.prepare('INSERT INTO places(name,city,country,latitude,longitude,average_score) VALUES (?,?,?,?,?,0)').run(name,city||'Unknown',country||'Unknown',Number(b.latitude),Number(b.longitude)).lastInsertRowid}} if(!place)return json(res,400,{error:'Выберите существующую локацию'}); if(b.ownership_confirmed!==true)return json(res,400,{error:'Подтвердите, что вы автор фотографии'}); const checked=validateImageData(b.image_url); if(checked.external)return json(res,400,{error:'Загрузите оригинальный файл, а не ссылку из интернета'}); const fp=await fingerprint(checked.bytes); const copy=findCopy(fp,db.prepare('SELECT * FROM image_fingerprints').all()); if(copy)return json(res,409,{error:'Эта фотография или похожая копия уже опубликована',duplicate_photo_id:copy.photo_id}); const image=await saveImage(b.image_url); const metrics = await processImage(image,{title:safe(b.title||'Untitled shot'),category:b.category,photo_type:b.photo_type});
 // Mark photos scored by the deterministic local model so leaderboards stay honest.
 if (metrics.provider && metrics.provider !== 'api') console.warn('[ai] photo stored with local fallback:',metrics.providerError)
    const photoType=['landscape','portrait','architecture','macro','street','night'].includes(b.photo_type)?b.photo_type:'landscape'; const id=db.prepare('INSERT INTO photos(user_id,place_id,image_url,title,description,category,photo_type,taken_at,created_at,ai_score,composition,lighting,sharpness,colors,visual_quality,error,ai_model) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(u.id,place.id,image,safe(b.title||'Untitled shot'),safe(b.description||''),['Landscape','Architecture','Nature','People','City','Night'].includes(b.category)?b.category:'City',photoType,safe(b.taken_at||'',40),now(),metrics.overallScore,metrics.composition,metrics.lighting,metrics.sharpness,metrics.colors,metrics.visualQuality,metrics.providerError||null,metrics.provider||null).lastInsertRowid; pendingUpload.set(u.id,id); db.prepare('INSERT INTO image_fingerprints(photo_id,sha256,visual_hash,canonical) VALUES (?,?,?,?)').run(id,fp.sha256,fp.visualHash,fp.canonical); db.prepare('UPDATE photos SET ai_model=?,error=? WHERE id=?').run(metrics.provider||'',metrics.providerError||null,id); pendingUpload.delete(u.id); const keys=['first-shot']; if(db.prepare('SELECT COUNT(*) c FROM photos WHERE user_id=?').get(u.id).c>=10)keys.push('photographer'); if(metrics.overallScore>90)keys.push('high-score'); for(const key of keys){const a=db.prepare('SELECT id FROM achievements WHERE key=?').get(key);if(a)db.prepare('INSERT OR IGNORE INTO user_achievements VALUES (?,?,?)').run(u.id,a.id,now())} return json(res,201,{photo:{id,image_url:image,...metrics}}) }
    if (req.method==='POST' && p.match(/^\/api\/places\/\d+\/favorite$/)) { const u=auth(req); if(!u)return json(res,401,{error:'Login required'}); const id=Number(p.split('/')[3]); if(!db.prepare('SELECT id FROM places WHERE id=?').get(id))return json(res,404,{error:'Place not found'}); const old=db.prepare('SELECT 1 FROM place_favorites WHERE user_id=? AND place_id=?').get(u.id,id); if(old)db.prepare('DELETE FROM place_favorites WHERE user_id=? AND place_id=?').run(u.id,id); else db.prepare('INSERT INTO place_favorites VALUES (?,?,?)').run(u.id,id,now()); return json(res,200,{saved:!old}) }
    const action=p.match(/^\/api\/photos\/(\d+)\/(like|favorite|rate)$/); if(req.method==='POST'&&action){const u=auth(req);if(!u)return json(res,401,{error:'Login required'});const [,id,type]=action;const b=await body(req);const uid=u.id;const photo=db.prepare('SELECT id,user_id,title FROM photos WHERE id=?').get(id);if(!photo)return json(res,404,{error:'Photo not found'});if(type==='like'){const old=db.prepare('SELECT 1 FROM likes WHERE user_id=? AND photo_id=?').get(uid,id);if(old){db.prepare('DELETE FROM likes WHERE user_id=? AND photo_id=?').run(uid,id);db.prepare('UPDATE photos SET likes=MAX(0,likes-1) WHERE id=?').run(id)}else{db.prepare('INSERT INTO likes VALUES (?,?,?)').run(uid,id,now());db.prepare('UPDATE photos SET likes=likes+1 WHERE id=?').run(id);if(photo.user_id!==uid)db.prepare('INSERT INTO notifications(user_id,type,message,created_at) VALUES (?,?,?,?)').run(photo.user_id,'like',`${u.username} liked “${photo.title}”`,now())}}else if(type==='favorite'){const old=db.prepare('SELECT 1 FROM favorites WHERE user_id=? AND photo_id=?').get(uid,id);if(old)db.prepare('DELETE FROM favorites WHERE user_id=? AND photo_id=?').run(uid,id);else db.prepare('INSERT INTO favorites VALUES (?,?,?)').run(uid,id,now())}else{const score=Math.max(1,Math.min(5,Number(b.score)));db.prepare('INSERT INTO ratings VALUES (?,?,?,?) ON CONFLICT(user_id,photo_id) DO UPDATE SET score=excluded.score').run(uid,id,score,now());db.prepare('UPDATE photos SET community_score=(SELECT ROUND(AVG(score),1) FROM ratings WHERE photo_id=?) WHERE id=?').run(id,id);if(photo.user_id!==uid)db.prepare('INSERT INTO notifications(user_id,type,message,created_at) VALUES (?,?,?,?)').run(photo.user_id,'rating',`${u.username} rated “${photo.title}” ${score}/5`,now())}return json(res,200,{ok:true})}
    return json(res,404,{error:'Not found'})
  } catch(e) { console.error('[api]',req.method,p,e); if(req.method==='POST'&&p==='/api/photos'&&u?.id&&pendingUpload?.get(u.id)){try{db.prepare('UPDATE photos SET error=?,ai_model=? WHERE id=?').run(String(e.message||'Request failed').slice(0,300),db.prepare('SELECT model FROM ai_settings WHERE id=1').get()?.model||'',pendingUpload.get(u.id))}catch{}finally{pendingUpload.delete(u.id)}} return json(res,e.message==='Authentication required'||e.message==='Login required'?401:400,{error:e.message.includes('UNIQUE')?'Already exists':e.message||'Request failed'}) }
}
function analyze(seed) { const n=Math.abs([...seed].reduce((a,c)=>a+c.charCodeAt(0),0)); const composition=78+n%19,lighting=74+(n>>2)%23,sharpness=80+(n>>3)%17,colors=82+(n>>4)%16,visualQuality=Math.round((composition+lighting+sharpness+colors)/4); return {composition,lighting,sharpness,colors,visualQuality,overallScore:visualQuality} }
const server=createServer(async(req,res)=>{const url=route(req);if(url.pathname.startsWith('/api/'))return api(req,res,url);if(url.pathname.startsWith('/uploads/')){const name=url.pathname.slice('/uploads/'.length).replace(/[^a-zA-Z0-9._-]/g,'');const full=normalize(join(uploadsDir,name));if(!full.startsWith(uploadsDir)||!existsSync(full))return json(res,404,{error:'Not found'});res.writeHead(200,{...securityHeaders,'Content-Type':`image/${extname(full).slice(1).replace('jpg','jpeg')}`,'Cache-Control':'public, max-age=31536000'});return res.end(await readFile(full))}const webRoot=existsSync(join(root,'dist','index.html'))?join(root,'dist'):root;let file=url.pathname==='/'?'index.html':url.pathname.replace(/^\//,'');let full=normalize(join(webRoot,file));if(!full.startsWith(webRoot)||!existsSync(full))return json(res,404,{error:'Not found'});const type={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json'}[extname(full)]||'application/octet-stream';res.writeHead(200,{'Content-Type':type});res.end(await readFile(full))})
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) server.listen(Number(process.env.PORT)||3001,()=>console.log(`ShotMap server: http://localhost:${process.env.PORT||3001}`))
export { analyze, validateImageData, server }
